[Unit]
Wants=buffyboard.service
Wants=buffyboard-vt-watch.service

[Service]
ExecStartPost=-/usr/bin/systemctl start buffyboard.service
ExecStartPost=-/usr/bin/systemctl start buffyboard-vt-watch.service
StandardError=journal
