# Global settings
source global-config.conf
source family-rk3506.conf

# Board-specific
BOARD=luckfox-lyra-zero-w
ENABLE_EXTENSIONS="unblock-rfkill"

# Enable the uinput module needed by buffyboard on the framebuffer console.
function custom_kernel_config__lyra_zero_console_keyboard() {
	opts_m+=(
		INPUT_UINPUT
	)
}
