# Global settings
source global-config.conf
source family-rv1106.conf

# Board-specific
BOARD=luckfox-pico-max
ENABLE_EXTENSIONS="$ENABLE_EXTENSIONS,pico-usb-auto"

# pico-max default to alpha channel for now
# Recently-merged configs are only present in Alpha (2.7.22)
MESHTASTICD_CHANNEL="alpha"
