# Global settings
# See https://docs.armbian.com/Developer-Guide_Build-Switches/
RELEASE=trixie
DOCKER_ARMBIAN_BASE_IMAGE="ubuntu:noble"
INSTALL_HEADERS=yes
INSTALL_ARMBIAN_FIRMWARE=yes
BUILD_DESKTOP=no
BUILD_MINIMAL=yes
DEB_COMPRESS=xz
# NetworkManager / nmcli is more user-friendly.
NETWORKING_STACK="network-manager"
EXTRAWIFI=yes
COMPRESS_OUTPUTIMAGE="xz,sha"
ENABLE_EXTENSIONS="meshtasticd"
