name: Build Armbian with Userpatches

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - ebyte-ecb41-pge
          - forlinx-ok3506-s12
          - luckfox-lyra-plus
          - luckfox-lyra-ultra-w
          - luckfox-lyra-zero-w
          - luckfox-pico-max
          - luckfox-pico-mini
          - raspberry-pi-64bit
          - uefi-x86_64
      fail-fast: false
    steps:
      - name: Checkout armbian/build into workspace root
        uses: actions/checkout@v6
        with:
          repository: armbian/build
          # Pin to "stable" Armbian tag 'v26.5.0' when released.
          # For now, a tested-working "trunk" tag is used.
          ref: 64c212859f3a715f4077b3d4ef50a587b49a6221
          # ref: v26.2.0-trunk.623

      - name: Checkout current repository into userpatches
        uses: actions/checkout@v6
        with:
          path: userpatches

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Compile ${{ matrix.config }} image
        shell: bash
        run: >
          ./compile.sh build ${{ matrix.config }}
          PREFER_DOCKER=yes
          KERNEL_CONFIGURE=no
          SHARE_LOGS=no

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config }}
          path: output/images/*
